/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_cawindowlogin (void);
GtkWidget* create_cawindowgdc (void);
GtkWidget* create_cawindowsecurit__ (void);
GtkWidget* create_cawindowet (void);
GtkWidget* create_cawindowajouter (void);
GtkWidget* create_cawindowmodifier (void);
GtkWidget* create_cawindowtache (void);
GtkWidget* create_acwrechercher (void);
GtkWidget* create_acwindowsupprimer (void);
