/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *cawindowlogin;
  GtkWidget *cawindowgdc;
  GtkWidget *cawindowsecurit__;
  GtkWidget *cawindowet;
  GtkWidget *cawindowajouter;
  GtkWidget *cawindowmodifier;
  GtkWidget *cawindowtache;
  GtkWidget *acwrechercher;
  GtkWidget *acwindowsupprimer;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  //cawindowlogin = create_cawindowlogin ();
  //gtk_widget_show (cawindowlogin);
  //cawindowgdc = create_cawindowgdc ();
  //gtk_widget_show (cawindowgdc);
  //cawindowsecurit__ = create_cawindowsecurit__ ();
  //gtk_widget_show (cawindowsecurit__);
  cawindowet = create_cawindowet ();
  gtk_widget_show (cawindowet);
  //cawindowajouter = create_cawindowajouter ();
  //gtk_widget_show (cawindowajouter);
  //cawindowmodifier = create_cawindowmodifier ();
  //gtk_widget_show (cawindowmodifier);
  //cawindowtache = create_cawindowtache ();
  //gtk_widget_show (cawindowtache);
  //acwrechercher = create_acwrechercher ();
  //gtk_widget_show (acwrechercher);
  //acwindowsupprimer = create_acwindowsupprimer ();
  //gtk_widget_show (acwindowsupprimer);

  gtk_main ();
  return 0;
}

